apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-api
  template:
    metadata:
      labels:
        app: devops-api
    spec:
      containers:
      - name: devops-api
        image: <sua-conta>.dkr.ecr.<sua-region>.amazonaws.com/devops-api:latest
        ports:
        - containerPort: 3000